# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kf8nvAh2XsrxfIozD3wWQuRPJK0IlA21
"""

import gradio as gr
import json
import uuid
import numpy as np
from datetime import datetime
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.backends import default_backend
import qrcode
from PIL import Image
import cv2
import random
import os

# ===============================
# LIGHT UI THEME
# ===============================
custom_css = """
body {
    background: linear-gradient(135deg, #f5f7fa, #c3cfe2);
    font-family: 'Segoe UI', sans-serif;
}

.gradio-container {
    background: transparent !important;
}

h1, h2, h3 {
    color: #1f2a44;
    text-align: center;
    font-weight: 600;
}

.card {
    background: #ffffff;
    border-radius: 18px;
    padding: 20px;
    box-shadow: 0px 8px 20px rgba(0,0,0,0.08);
    border: 1px solid #e6e6e6;
}

input, textarea, select {
    border-radius: 10px !important;
    border: 1px solid #d0d7de !important;
}

button {
    background: #4a90e2 !important;
    color: white !important;
    border-radius: 10px !important;
    font-weight: 500;
    border: none !important;
}

button:hover {
    background: #357ABD !important;
    transform: translateY(-1px);
    box-shadow: 0px 5px 12px rgba(0,0,0,0.12);
}
"""

# ===============================
# KEY MANAGEMENT (PERSISTENT)
# ===============================

if os.path.exists("fernet.key"):
    with open("fernet.key", "rb") as f:
        encryption_key = f.read()
else:
    encryption_key = Fernet.generate_key()
    with open("fernet.key", "wb") as f:
        f.write(encryption_key)

fernet = Fernet(encryption_key)

if os.path.exists("private_key.pem"):
    with open("private_key.pem", "rb") as f:
        private_key = serialization.load_pem_private_key(
            f.read(),
            password=None,
            backend=default_backend()
        )
else:
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )
    with open("private_key.pem", "wb") as f:
        f.write(
            private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption()
            )
        )

public_key = private_key.public_key()

# ===============================
# OTP STORAGE
# ===============================
otp_store = {}

# ===============================
# LOGGING
# ===============================
def log_transaction(data):
    with open("transactions.log", "a") as f:
        f.write(json.dumps(data) + "\n")

# ===============================
# RISK ANALYSIS
# ===============================
def assess_risk(transaction):
    score = 0

    if transaction["Amount"] > 2000:
        score += 3
    elif transaction["Amount"] > 500:
        score += 2
    else:
        score += 1

    if score >= 3:
        return "High"
    elif score == 2:
        return "Medium"
    else:
        return "Low"

# ===============================
# GENERATE QR
# ===============================
def generate_secure_qr(user_id, amount, currency, merchant_id):

    transaction_id = str(uuid.uuid4())

    transaction = {
        "TransactionID": transaction_id,
        "UserID": user_id,
        "Amount": float(amount),
        "Currency": currency,
        "MerchantID": merchant_id,
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    transaction_json = json.dumps(transaction)

    encrypted_data = fernet.encrypt(transaction_json.encode())
    encrypted_str = encrypted_data.decode()

    signature = private_key.sign(
        encrypted_data,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    payload = f"ENC_DATA:{encrypted_str}|SIG:{signature.hex()}"

    qr = qrcode.QRCode(box_size=10, border=4)
    qr.add_data(payload)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    log_transaction(transaction)

    return img.convert("RGB"), transaction_json

# ===============================
# VERIFY QR
# ===============================
def verify_qr(uploaded_image):

    if uploaded_image is None:
        return "No image uploaded ❌", "", "", ""

    img = cv2.cvtColor(np.array(uploaded_image), cv2.COLOR_RGB2BGR)
    detector = cv2.QRCodeDetector()
    data, _, _ = detector.detectAndDecode(img)

    if not data:
        return "QR Code not detected ❌", "", "", ""

    try:
        parts = data.split("|SIG:")
        encrypted_str = parts[0].replace("ENC_DATA:", "")
        signature_hex = parts[1]

        encrypted_bytes = encrypted_str.encode()
        signature = bytes.fromhex(signature_hex)

        public_key.verify(
            signature,
            encrypted_bytes,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )

        decrypted = fernet.decrypt(encrypted_bytes).decode()
        transaction = json.loads(decrypted)

        risk = assess_risk(transaction)
        tx_id = transaction["TransactionID"]

        if risk == "High":
            return "✅ Signature Valid", decrypted, "HIGH RISK", "🚫 BLOCKED"

        elif risk == "Medium":
            otp_store[tx_id] = str(random.randint(100000, 999999))
            return (
                "✅ Signature Valid",
                decrypted,
                "MEDIUM RISK",
                f"⚠ OTP Required (Demo OTP: {otp_store[tx_id]})"
            )

        else:
            return "✅ Signature Valid", decrypted, "LOW RISK", "✅ APPROVED"

    except Exception:
        return "❌ Signature Verification FAILED", "", "", "🚫 STOPPED"

# ===============================
# OTP VERIFY
# ===============================
def verify_otp(tx_id, user_input):

    if tx_id not in otp_store:
        return "No OTP required or expired."

    if user_input == otp_store[tx_id]:
        del otp_store[tx_id]
        return "✅ OTP Correct — Transaction Approved"

    return "❌ Incorrect OTP — Transaction Blocked"

# ===============================
# UI
# ===============================
with gr.Blocks(css=custom_css) as demo:

    gr.Markdown("# 🔐 Secure AI-Driven QR Payment System")

    with gr.Tab("Generate QR"):
        with gr.Column():

            user_id = gr.Textbox(label="User ID", value="USER001")
            amount = gr.Number(label="Amount", value=150)
            currency = gr.Dropdown(["USD", "EUR", "INR"], value="USD")
            merchant = gr.Textbox(label="Merchant ID", value="MERCH001")

            btn = gr.Button("Generate QR")

            qr_out = gr.Image(label="QR Code")
            json_out = gr.Textbox(label="Transaction JSON")

            btn.click(generate_secure_qr,
                      inputs=[user_id, amount, currency, merchant],
                      outputs=[qr_out, json_out])

    with gr.Tab("Verify QR"):
        with gr.Column():

            upload = gr.Image(label="Upload QR Code")
            verify_btn = gr.Button("Verify Transaction")

            sig = gr.Textbox(label="Signature Status")
            dec = gr.Textbox(label="Decrypted Data")
            risk = gr.Textbox(label="Risk Level")
            action = gr.Textbox(label="System Action")

            verify_btn.click(verify_qr,
                             inputs=upload,
                             outputs=[sig, dec, risk, action])

        gr.Markdown("### OTP Verification (Medium Risk)")
        tx_id = gr.Textbox(label="Transaction ID")
        otp = gr.Textbox(label="Enter OTP")
        otp_btn = gr.Button("Verify OTP")
        otp_out = gr.Textbox()

        otp_btn.click(verify_otp,
                      inputs=[tx_id, otp],
                      outputs=otp_out)

demo.launch()